Updated tool versions and refined scripts in `revive-old-iam-user` and `injectdylib` TTPs.
**Added:**

- Enhanced error handling in `revive-old-iam-user` TTP to ensure input validation for user and access key ID.
- Expanded description and provided pre-requisites section in `injectdylib` TTP for better understanding and usage.

**Changed:**

- Bumped versions of `golang` and `python` in `.tool-versions` for keeping up with the latest stable releases.
- Modified variable names and replaced dashes with underscores in `revive-old-iam-user` TTP for consistency and adherence to naming conventions.
- Improved the formatting and indentation in `revive-old-iam-user` TTP for better readability and maintenance.
- Reorganized the `cleanup` section in `revive-old-iam-user` TTP to encapsulate the `delete_key` function, ensuring better scoping and readability.

diff --git a/ttps/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml b/ttps/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml
--- a/ttps/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml
+++ b/ttps/cloud/aws/iam/revive-old-iam-user/revive-old-iam-user.yaml
@@ -39,57 +39,69 @@ steps:
         echo -e "AWS CLI is installed: $(aws --version)"
       fi
 
-  - name: add-access-key
+  - name: add_access_key
     inline: |
       set -e
 
       function create_key() {
-        local USER=$1
+        local user=$1
 
         # Create a new key
-        new_key=$(aws iam create-access-key --user-name $USER)
+        new_key=$(aws iam create-access-key --user-name $user)
 
         # Extract new access key id
         new_access_key_id=$(echo $new_key | jq -r '.AccessKey.AccessKeyId')
 
         # Store the new list of keys
-        keys_after=$(aws iam list-access-keys --user-name $USER --query 'AccessKeyMetadata[].AccessKeyId' --output text)
+        keys_after=$(aws iam list-access-keys --user-name $user --query 'AccessKeyMetadata[].AccessKeyId' --output text)
 
         # Confirm that a new key has been added
         if [[ "$keys_after" == *"$new_access_key_id"* ]]; then
           echo $new_access_key_id
         else
-          echo "Failed to add new key for $USER"
+          echo "Failed to add new key for $user"
           exit 1
         fi
       }
 
-      function delete_key() {
-        local USER=$1
-        local new_access_key_id=$2
-
-        aws iam delete-access-key --access-key-id $new_access_key_id --user-name $USER
-
-        # Confirm that the key has been deleted
-        keys_final=$(aws iam list-access-keys --user-name $USER --query 'AccessKeyMetadata[].AccessKeyId' --output text)
-
-        if [[ "$keys_final" != *"$new_access_key_id"* ]]; then
-          echo "Key $new_access_key_id has been deleted for $USER"
-        else
-          echo "Failed to delete key for $USER"
-          exit 1
-        fi
-      }
-
-      USER="{{ .Args.user }}"
-      new_key_id=$(create_key $USER)
+      new_access_key=$(create_key {{ .Args.user }})
+      # Output value to pick up output in the cleanup step
+      echo "$new_access_key"
 
     cleanup:
       name: cleanup
       inline: |
         set -e
 
-        delete_key $USER $new_key_id
+        function delete_key() {
+          local user=$1
+          local new_access_key_id=$2
+
+          # Ensure a user and new_access_key_id are provided
+          if [[ -z "$user" ]] || [[ -z "$new_access_key_id" ]]; then
+              if [[ -z "$user" ]]; then
+                  echo "Error: User must be provided."
+              fi
+              if [[ -z "$new_access_key_id" ]]; then
+                  echo "Error: Access key ID must be provided."
+              fi
+              exit 1
+          fi
+
+          aws iam delete-access-key --access-key-id $new_access_key_id --user-name $user
+
+          # Confirm that the key has been deleted
+          keys_final=$(aws iam list-access-keys --user-name $user --query 'AccessKeyMetadata[].AccessKeyId' --output text)
+
+          if [[ "$keys_final" != *"$new_access_key_id"* ]]; then
+            echo "Key $new_access_key_id has been deleted for $user"
+          else
+            echo "Failed to delete key for $user"
+            exit 1
+          fi
+        }
+
+        delete_key "{{ .Args.user }}" $forge.steps.add_access_key.stdout
 
   - name: check-detection
     inline: |
@@ -101,11 +113,11 @@ steps:
         }
 
         ten_minutes_ago() {
-        if [[ "$OSTYPE" == "darwin"* ]]; then
-            date -v-10M -u +'%Y-%m-%dT%H:%M:%SZ'
-        else
-            date -u -d '10 minutes ago' +'%Y-%m-%dT%H:%M:%SZ'
-        fi
+            if [[ "$OSTYPE" == "darwin"* ]]; then
+                date -v-10M -u +'%Y-%m-%dT%H:%M:%SZ'
+            else
+                date -u -d '10 minutes ago' +'%Y-%m-%dT%H:%M:%SZ'
+            fi
         }
 
         # Define a time window for CloudTrail lookup
@@ -122,9 +134,10 @@ steps:
                 --end-time $END_TIME \
                 --region us-east-1)
 
-            # If there are recent events
-            if [[ "$(echo "$EVENTS" | jq -r '.Events | length')" -gt 0 ]]; then
-                echo "Recent $event_name events detected."
+            EVENT_COUNT=$(echo "$EVENTS" | jq -r '.Events | length')
+
+            if [[ "$EVENT_COUNT" -gt 0 ]]; then
+                echo "Detected $EVENT_COUNT recent $event_name events."
             else
                 echo "No recent $event_name events detected."
             fi
